channels:
  - conda-forge
dependencies:
  - python=3
  - bokeh=0.13
  - dask=0.19.4
  - dask-ml=0.10.0
  - distributed=1.23.3
  - jupyterlab=0.35.1
  - nodejs=8.9
  - numpy
  - pandas
  - pyarrow==0.10.0
  - scikit-learn=0.20
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - py-xgboost
  - pip:
    - graphviz
    - dask_xgboost
    - seaborn
    - mimesis
