name: dask-examples
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh=2.2.3
  - dask=2.20.0
  - dask-image=0.2.0
  - dask-ml=1.6.0
  - dask-labextension=2.0.2
  - jupyterlab=2.1
  - nodejs=16
  - numba
  - numpy=1.21
  - pip
  - pandas=1.3
  - pyarrow
  - python-graphviz
  - seaborn
  - scikit-learn=0.23
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - xarray
  - pooch
  - bottleneck
  - requests
  - py-xgboost
  - dask-xgboost
  - pip:
      - mimesis
      - pystan==2.19.1.1
      - prophet
