channels:
  - conda-forge
dependencies:
  - python=3.7
  - bokeh=1.3.1
  - dask=2.2
  - dask-image=0.2.0
  - dask-ml=1.0.0
  # Installing dev version of fsspec until there's a new release with
  # changes from https://github.com/intake/filesystem_spec/pull/128
  # - fsspec>=0.4
  - jupyterlab>=1.0
  - nodejs=8.9
  - notebook<5.7.5
  - tornado=5
  - numba
  - numpy=1.16
  - pip
  - pandas=0.25
  - pyarrow==0.14.1
  - python-graphviz
  - seaborn
  - scikit-learn=0.20
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - xarray
  - bottleneck
  - requests
  - py-xgboost
  - pip:
    - dask_xgboost
    - mimesis
    - dask-labextension>=1.0.3
    - git+https://github.com/intake/filesystem_spec
