channels:
  - conda-forge
dependencies:
  - python=3
  - bokeh=1.0.4
  - dask=1.1.5
  - dask-image=0.2.0
  - dask-ml=0.12.0
  - nodejs=8.9
  - notebook<5.7.5
  - tornado=5
  - numpy
  - pandas
  - pyarrow==0.10.0
  - python-graphviz
  - seaborn
  - scikit-learn=0.20
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - xarray
  - bottleneck
  - py-xgboost
  - pip:
    - dask_xgboost
    - mimesis
    - jupyterlab==1.0.0a3
    - dask-labextension==0.3.3
