channels:
  - defaults
dependencies:
  - dask==0.18.1
  - dask-ml==0.6.0
  - distributed==1.22.0
  - numpy
  - pandas
  - pyarrow==0.9.0
  - scikit-learn
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - py-xgboost
  - pip:
    - graphviz
    - dask_xgboost
    - seaborn
    - git+https://github.com/mrocklin/dask@dataframes-binder
