channels:
  - conda-forge
dependencies:
  - python=3
  - bokeh=1.0.4
  - dask=1.1.4
  - dask-ml=0.12.0
  - dask_xgboost
  - distributed=1.26
  - jupyterlab=0.35.1
  - nodejs=8.9
  - numpy
  - pandas
  - pyarrow==0.10.0
  - python-graphviz
  - seaborn
  - scikit-learn=0.20
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - xarray
  - bottleneck
  - py-xgboost
  - pip:
    - mimesis
