channels:
  - conda-forge
dependencies:
  - python=3
  - bokeh=1.1.0
  - dask=1.2
  - dask-image=0.2.0
  - dask-ml=1.0.0
  - nodejs=8.9
  - notebook<5.7.5
  - tornado=5
  - numba
  - numpy
  - pip
  - pandas
  - pyarrow==0.12.0
  - python-graphviz
  - seaborn
  - scikit-learn=0.20
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - xarray
  - bottleneck
  - requests
  - py-xgboost
  - pip:
    - dask_xgboost
    - mimesis
    - jupyterlab==1.0.0a8
    - dask-labextension==0.4.0a1
