channels:
  - defaults
dependencies:
  - dask==0.17.2
  - dask-ml==0.6.0
  - distributed==1.21.6
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - py-xgboost
  - pip:
    - graphviz
    - dask_xgboost
    - seaborn